--Task 6
SELECT 
	S.STORE_NAME,
	S.STORE_ID,
	SUM(OI.QUANTITY) AS TOTAL_ITEMS_SOLD
FROM STORES S 
INNER JOIN ORDERS O
ON O.STORE_ID = S.STORE_ID 
INNER JOIN ORDER_ITEMS OI
ON OI.ORDER_ID = O.ORDER_ID 
GROUP BY S.STORE_NAME, S.STORE_ID  

--Task 7
SELECT 
	C.CUSTOMER_ID,
	C.FIRST_NAME,
	C.LAST_NAME
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL 

--Task 8
SELECT 
	P.PRODUCT_ID,
	P.PRODUCT_NAME,
	P.LIST_PRICE
FROM PRODUCTS P 
LEFT JOIN ORDER_ITEMS OI
ON P.PRODUCT_ID = OI.PRODUCT_ID
WHERE OI.ORDER_ID IS NULL 
ORDER BY P.LIST_PRICE DESC 

--Task 9
SELECT 
	P.PRODUCT_NAME,
	B.BRAND_NAME,
	SUM(OI.QUANTITY) AS TOTAL_ITEMS_SOLD,
	SUM(OI.LIST_PRICE * OI.QUANTITY) AS TOTAL_REVENUE
FROM BRANDS B 
INNER JOIN PRODUCTS P 
ON P.BRAND_ID = B.BRAND_ID 
INNER JOIN ORDER_ITEMS OI 
ON P.PRODUCT_ID  = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME, B.BRAND_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10 

--Task 10
SELECT 
	S.STORE_NAME,
	SUM(OI.LIST_PRICE * OI.QUANTITY) AS TOTAL_REVENUE
FROM STORES S 
LEFT JOIN ORDERS O
ON S.STORE_ID = O.STORE_ID
LEFT JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY S.STORE_NAME, S.STORE_ID
ORDER BY TOTAL_REVENUE DESC
