/*
============================================================
04 — Advanced JOINs
============================================================

This file contains advanced SQL JOIN exercises
using the BikeStores database.

Topics:
- Multiple JOINs
- LEFT JOIN
- NULL handling
- Aggregation
- GROUP BY
- HAVING
- Business metrics
- Revenue analysis

Database:
- PostgreSQL
- BikeStores
============================================================
*/


/*
============================================================
Task 6: Store Performance
============================================================

Business Question:
Calculate the total number of items sold by each store.
============================================================
*/

SELECT
    s.store_id,
    s.store_name,
    SUM(oi.quantity) AS total_items_sold
FROM stores AS s
INNER JOIN orders AS o
    ON o.store_id = s.store_id
INNER JOIN order_items AS oi
    ON oi.order_id = o.order_id
GROUP BY
    s.store_id,
    s.store_name;


/*
============================================================
Task 7: Customers Without Orders
============================================================

Business Question:
Find all registered customers who have never placed
an order.
============================================================
*/

SELECT
    c.customer_id,
    c.first_name,
    c.last_name
FROM customers AS c
LEFT JOIN orders AS o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


/*
============================================================
Task 8: Products Never Ordered
============================================================

Business Question:
Find products that have never been included
in any order.
============================================================
*/

SELECT
    p.product_id,
    p.product_name,
    p.list_price
FROM products AS p
LEFT JOIN order_items AS oi
    ON p.product_id = oi.product_id
WHERE oi.order_id IS NULL
ORDER BY
    p.list_price DESC;


/*
============================================================
Task 9: Best-Selling Products
============================================================

Business Question:
Identify the 10 products with the highest total revenue.
============================================================
*/

SELECT
    p.product_name,
    b.brand_name,
    SUM(oi.quantity) AS total_items_sold,
    SUM(oi.list_price * oi.quantity) AS total_revenue
FROM brands AS b
INNER JOIN products AS p
    ON p.brand_id = b.brand_id
INNER JOIN order_items AS oi
    ON p.product_id = oi.product_id
GROUP BY
    p.product_name,
    b.brand_name
ORDER BY
    total_revenue DESC
LIMIT 10;


/*
============================================================
Task 10: Store Revenue
============================================================

Business Question:
Calculate the total revenue generated by each store
and rank stores from highest to lowest revenue.
============================================================
*/

SELECT
    s.store_name,
    COALESCE(
        SUM(oi.list_price * oi.quantity),
        0
    ) AS total_revenue
FROM stores AS s
LEFT JOIN orders AS o
    ON s.store_id = o.store_id
LEFT JOIN order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY
    s.store_name,
    s.store_id
ORDER BY
    total_revenue DESC;
