-- ============================================
-- Task 1 — Top Customers by Revenue
-- Find customers whose total spending exceeds 50,000.
-- ============================================
WITH TEMP_CUSTOMER AS (
	SELECT 
		C.CUSTOMER_ID,
		C.FIRST_NAME,
		C.LAST_NAME,
		SUM(OI.LIST_PRICE * OI.QUANTITY) AS TOTAL_SPENT,
		COUNT(DISTINCT O.ORDER_ID) AS ORDERS_COUNT
	FROM CUSTOMERS C 
	INNER JOIN ORDERS O 
	ON C.CUSTOMER_ID = O.CUSTOMER_ID 
	INNER JOIN ORDER_ITEMS OI
	ON O.ORDER_ID = OI.ORDER_ID
	GROUP BY C.CUSTOMER_ID,
		C.FIRST_NAME,
		C.LAST_NAME
)
SELECT *
FROM TEMP_CUSTOMER TC
WHERE TC.TOTAL_SPENT > 50000
ORDER BY TC.TOTAL_SPENT DESC 

-- ============================================
-- Task 2 — Best-Selling Product in Each Category
-- Find the best-selling product by quantity in each category.
-- Include all products in case of a tie.
-- ============================================
WITH TEMP_CATEGORY AS (
	SELECT 
		C.CATEGORY_NAME,
		P.PRODUCT_ID,
		P.PRODUCT_NAME,
		SUM(OI.QUANTITY) AS TOTAL_QUANTITY_SOLD
	FROM CATEGORIES C 
	INNER JOIN PRODUCTS P 
	ON C.CATEGORY_ID = P.CATEGORY_ID
	INNER JOIN ORDER_ITEMS OI 
	ON P.PRODUCT_ID = OI.PRODUCT_ID 
	GROUP BY C.CATEGORY_NAME, C.CATEGORY_ID,
		P.PRODUCT_ID,
		P.PRODUCT_NAME
),
MAX_QUANTITY_SOLD AS(
	SELECT 
		TC.CATEGORY_NAME,
		MAX(TOTAL_QUANTITY_SOLD) AS MAX_QUANTITY_SOLD 
	FROM TEMP_CATEGORY TC
	GROUP BY TC.CATEGORY_NAME
)
SELECT *
FROM TEMP_CATEGORY TC
INNER JOIN MAX_QUANTITY_SOLD MS
ON TC.CATEGORY_NAME = MS.CATEGORY_NAME 
WHERE TC.TOTAL_QUANTITY_SOLD = MS.MAX_QUANTITY_SOLD
ORDER BY TC.CATEGORY_NAME

-- ============================================
-- Task 3 — Stores Above Average Revenue
-- Find stores whose revenue is above the average revenue
-- across all stores and calculate the difference from average.
-- ============================================
WITH TEMP_STORES AS (
	SELECT 
		S.STORE_ID,
		S.STORE_NAME,
		SUM(OI.LIST_PRICE * OI.QUANTITY) AS TOTAL_REVENUE
	FROM STORES S 
	INNER JOIN ORDERS O
	ON S.STORE_ID = O.STORE_ID
	INNER JOIN ORDER_ITEMS OI 
	ON O.ORDER_ID = OI.ORDER_ID
	GROUP BY S.STORE_ID,
		S.STORE_NAME
),
AVG_REVENUE AS (
	SELECT AVG(TOTAL_REVENUE) AS AVG_REVENUE
	FROM TEMP_STORES TS
) 
SELECT 
	TS.STORE_ID,
	TS.STORE_NAME,
	TS.TOTAL_REVENUE,
	(TS.TOTAL_REVENUE - AR.AVG_REVENUE) AS DIFFERENCE_FROM_AVERAGE
FROM TEMP_STORES TS
CROSS JOIN AVG_REVENUE AR
WHERE TS.TOTAL_REVENUE > AR.AVG_REVENUE 
ORDER BY TS.TOTAL_REVENUE DESC


-- ============================================
-- Task 4 — Customers With Increasing Activity
-- Find customers with at least 2 orders whose latest order
-- date is later than their first order date.
-- ============================================
WITH ORDERS_OF_CUSTOMER AS (
	SELECT  
		C.CUSTOMER_ID,
		C.FIRST_NAME,
		C.LAST_NAME,
		MIN(O.ORDER_DATE) AS FIRST_ORDER_DATE,
		MAX(O.ORDER_DATE) AS LAST_ORDER_DATE,
		COUNT(DISTINCT O.ORDER_ID) AS ORDERS_COUNT
	FROM CUSTOMERS C 
	INNER JOIN ORDERS O
	ON C.CUSTOMER_ID = O.CUSTOMER_ID
	GROUP BY C.CUSTOMER_ID,
		C.FIRST_NAME,
		C.LAST_NAME
)
SELECT *
FROM ORDERS_OF_CUSTOMER OC
WHERE OC.ORDERS_COUNT >= 2
  AND OC.LAST_ORDER_DATE > OC.FIRST_ORDER_DATE
ORDER BY OC.LAST_ORDER_DATE DESC

-- ============================================
-- Task 5 — Brand Performance Analysis
-- Find brands whose revenue is above the average brand revenue.
-- Calculate products sold, average revenue per sold item,
-- and the difference from average brand revenue.
-- ============================================
WITH TEMP_BRAND AS (
	SELECT 
		B.BRAND_ID,
		B.BRAND_NAME,
		SUM(OI.LIST_PRICE * OI.QUANTITY) AS TOTAL_REVENUE,
		SUM(OI.QUANTITY) AS PRODUCTS_SOLD
	FROM BRANDS B 
	INNER JOIN PRODUCTS P 
	ON B.BRAND_ID = P.BRAND_ID
	INNER JOIN ORDER_ITEMS OI 
	ON P.PRODUCT_ID = OI.PRODUCT_ID
	GROUP BY B.BRAND_ID,
			B.BRAND_NAME
),
AVR_REVENUE AS (
	SELECT 
		AVG(TB.TOTAL_REVENUE) AS AVERAGE_BRAND_REVENUE
	FROM TEMP_BRAND TB 
)
SELECT *, 
	(TB.TOTAL_REVENUE - AR.AVERAGE_BRAND_REVENUE) AS DIFFERENCE_FROM_AVERAGE, 
	(TB.TOTAL_REVENUE / TB.PRODUCTS_SOLD) AS AVG_PRODUCT_REVENUE
FROM TEMP_BRAND TB
CROSS JOIN AVR_REVENUE AR
WHERE TB.TOTAL_REVENUE > AR.AVERAGE_BRAND_REVENUE 
ORDER BY TB.TOTAL_REVENUE DESC 
